
import { CharacterData, Animal } from './types';

export const RADICALS_DATA: CharacterData[] = [
  { char: "一", pinyin: "yī", meaning: "one" },
  { char: "丨", pinyin: "gǔn", meaning: "line" },
  { char: "丶", pinyin: "zhǔ", meaning: "dot" },
  { char: "丿", pinyin: "piě", meaning: "slash" },
  { char: "乙", pinyin: "yǐ", meaning: "second" },
  { char: "亅", pinyin: "jué", meaning: "hook" },
  { char: "二", pinyin: "èr", meaning: "two" },
  { char: "亠", pinyin: "tóu", meaning: "lid" },
  { char: "人", pinyin: "rén", meaning: "man" },
  { char: "儿", pinyin: "ér", meaning: "son / legs" },
  { char: "入", pinyin: "rù", meaning: "enter" },
  { char: "八", pinyin: "bā", meaning: "eight" },
  { char: "冂", pinyin: "jiōng", meaning: "down box" },
  { char: "冖", pinyin: "mì", meaning: "cover" },
  { char: "冫", pinyin: "bīng", meaning: "ice" },
  { char: "几", pinyin: "jī", meaning: "table" },
  { char: "凵", pinyin: "qū", meaning: "open box" },
  { char: "刀", pinyin: "dāo", meaning: "knife" },
  { char: "力", pinyin: "lì", meaning: "power" },
  { char: "勹", pinyin: "bāo", meaning: "wrap" },
  { char: "匕", pinyin: "bǐ", meaning: "spoon" },
  { char: "匚", pinyin: "fāng", meaning: "right open box" },
  { char: "十", pinyin: "shí", meaning: "ten" },
  { char: "卜", pinyin: "bǔ", meaning: "divination" },
  { char: "卩", pinyin: "jié", meaning: "seal" },
  { char: "厂", pinyin: "hǎn", meaning: "cliff" },
  { char: "厶", pinyin: "sī", meaning: "private" },
  { char: "又", pinyin: "yòu", meaning: "again" },
  { char: "口", pinyin: "kǒu", meaning: "mouth" },
  { char: "囗", pinyin: "wéi", meaning: "enclosure" },
  { char: "土", pinyin: "tǔ", meaning: "earth" },
  { char: "士", pinyin: "shì", meaning: "scholar" },
  { char: "夕", pinyin: "xī", meaning: "sunset" },
  { char: "大", pinyin: "dà", meaning: "big" },
  { char: "女", pinyin: "nǚ", meaning: "woman" },
  { char: "子", pinyin: "zǐ", meaning: "child" },
  { char: "宀", pinyin: "mián", meaning: "roof" },
  { char: "寸", pinyin: "cùn", meaning: "inch" },
  { char: "小", pinyin: "xiǎo", meaning: "small" },
  { char: "尸", pinyin: "shī", meaning: "corpse" },
  { char: "山", pinyin: "shān", meaning: "mountain" },
  { char: "工", pinyin: "gōng", meaning: "work" },
  { char: "己", pinyin: "jǐ", meaning: "self" },
  { char: "巾", pinyin: "jīn", meaning: "turban" },
  { char: "干", pinyin: "gān", meaning: "dry" },
  { char: "弓", pinyin: "gōng", meaning: "bow" },
  { char: "心", pinyin: "xīn", meaning: "heart" },
  { char: "戈", pinyin: "gē", meaning: "halberd" },
  { char: "手", pinyin: "shǒu", meaning: "hand" },
  { char: "日", pinyin: "rì", meaning: "sun" },
  { char: "月", pinyin: "yuè", meaning: "moon" },
  { char: "木", pinyin: "mù", meaning: "tree" },
  { char: "水", pinyin: "shuǐ", meaning: "water" },
  { char: "火", pinyin: "huǒ", meaning: "fire" },
  { char: "犬", pinyin: "quǎn", meaning: "dog" },
  { char: "玉", pinyin: "yù", meaning: "jade" },
  { char: "生", pinyin: "shēng", meaning: "life" },
  { char: "用", pinyin: "yòng", meaning: "use" },
  { char: "田", pinyin: "tián", meaning: "field" },
  { char: "目", pinyin: "mù", meaning: "eye" },
  { char: "石", pinyin: "shí", meaning: "stone" },
  { char: "竹", pinyin: "zhú", meaning: "bamboo" },
  { char: "米", pinyin: "mǐ", meaning: "rice" },
  { char: "糸", pinyin: "mì", meaning: "silk" },
  { char: "羊", pinyin: "yáng", meaning: "sheep" },
  { char: "耳", pinyin: "ěr", meaning: "ear" },
  { char: "肉", pinyin: "ròu", meaning: "meat" },
  { char: "自", pinyin: "zì", meaning: "self" },
  { char: "舟", pinyin: "zhōu", meaning: "boat" },
  { char: "虫", pinyin: "chóng", meaning: "insect" },
  { char: "衣", pinyin: "yī", meaning: "clothes" },
  { char: "言", pinyin: "yán", meaning: "speech" },
  { char: "走", pinyin: "zǒu", meaning: "run" },
  { char: "足", pinyin: "zú", meaning: "foot" },
  { char: "金", pinyin: "jīn", meaning: "gold" },
  { char: "門", pinyin: "mén", meaning: "gate" },
  { char: "雨", pinyin: "yǔ", meaning: "rain" },
  { char: "食", pinyin: "shí", meaning: "eat" },
  { char: "馬", pinyin: "mǎ", meaning: "horse" },
  { char: "魚", pinyin: "yú", meaning: "fish" },
  { char: "鳥", pinyin: "niǎo", meaning: "bird" },
  { char: "鼻", pinyin: "bí", meaning: "nose" },
  { char: "龍", pinyin: "lóng", meaning: "dragon" }
];

export const NUMBERS_DATA: CharacterData[] = [
  { char: "零", pinyin: "líng", meaning: "zero" },
  { char: "一", pinyin: "yī", meaning: "one" },
  { char: "二", pinyin: "èr", meaning: "two" },
  { char: "三", pinyin: "sān", meaning: "three" },
  { char: "四", pinyin: "sì", meaning: "four" },
  { char: "五", pinyin: "wǔ", meaning: "five" },
  { char: "六", pinyin: "liù", meaning: "six" },
  { char: "七", pinyin: "qī", meaning: "seven" },
  { char: "八", pinyin: "bā", meaning: "eight" },
  { char: "九", pinyin: "jiǔ", meaning: "nine" },
  { char: "十", pinyin: "shí", meaning: "ten" }
];

export const ANIMALS: Animal[] = [
  { emoji: "🐼", name: "Panda", message: "You're doing great!" },
  { emoji: "🐯", name: "Tiger", message: "Keep fighting!" },
  { emoji: "🦊", name: "Fox", message: "Clever choice!" },
  { emoji: "🐰", name: "Rabbit", message: "Fast learner!" },
  { emoji: "🦁", name: "Lion", message: "Roaring success!" },
  { emoji: "🐨", name: "Koala", message: "Stay calm and study." },
  { emoji: "🦉", name: "Owl", message: "Wise moves." },
  { emoji: "🐸", name: "Frog", message: "Hop to it!" }
];
