
import { CharacterData, Animal } from './types';

export const RADICALS_DATA: CharacterData[] = [
  { char: "一", pinyin: "yī", meaning: "one" },
  { char: "丨", pinyin: "gǔn", meaning: "line" },
  { char: "丶", pinyin: "zhǔ", meaning: "dot" },
  { char: "丿", pinyin: "piě", meaning: "slash" },
  { char: "乙", pinyin: "yǐ", meaning: "second" },
  { char: "亅", pinyin: "jué", meaning: "hook" },
  { char: "二", pinyin: "èr", meaning: "two" },
  { char: "亠", pinyin: "tóu", meaning: "lid" },
  { char: "人", pinyin: "rén", meaning: "man" },
  { char: "儿", pinyin: "ér", meaning: "son / legs" },
  { char: "入", pinyin: "rù", meaning: "enter" },
  { char: "八", pinyin: "bā", meaning: "eight" },
  { char: "冂", pinyin: "jiōng", meaning: "down box" },
  { char: "冖", pinyin: "mì", meaning: "cover" },
  { char: "冫", pinyin: "bīng", meaning: "ice" },
  { char: "几", pinyin: "jī", meaning: "table" },
  { char: "凵", pinyin: "qū", meaning: "open box" },
  { char: "刀", pinyin: "dāo", meaning: "knife" },
  { char: "力", pinyin: "lì", meaning: "power" },
  { char: "勹", pinyin: "bāo", meaning: "wrap" },
  { char: "匕", pinyin: "bǐ", meaning: "spoon" },
  { char: "匚", pinyin: "fāng", meaning: "right open box" },
  { char: "匸", pinyin: "xì", meaning: "hiding enclosure" },
  { char: "十", pinyin: "shí", meaning: "ten" },
  { char: "卜", pinyin: "bǔ", meaning: "divination" },
  { char: "卩", pinyin: "jié", meaning: "seal" },
  { char: "厂", pinyin: "hǎn", meaning: "cliff" },
  { char: "厶", pinyin: "sī", meaning: "private" },
  { char: "又", pinyin: "yòu", meaning: "again" },
  { char: "口", pinyin: "kǒu", meaning: "mouth" },
  { char: "囗", pinyin: "wéi", meaning: "enclosure" },
  { char: "土", pinyin: "tǔ", meaning: "earth" },
  { char: "士", pinyin: "shì", meaning: "scholar" },
  { char: "夂", pinyin: "zhǐ", meaning: "go" },
  { char: "夊", pinyin: "suī", meaning: "go slowly" },
  { char: "夕", pinyin: "xī", meaning: "sunset" },
  { char: "大", pinyin: "dà", meaning: "big" },
  { char: "女", pinyin: "nǚ", meaning: "woman" },
  { char: "子", pinyin: "zǐ", meaning: "child" },
  { char: "宀", pinyin: "mián", meaning: "roof" },
  { char: "寸", pinyin: "cùn", meaning: "inch" },
  { char: "小", pinyin: "xiǎo", meaning: "small" },
  { char: "尢", pinyin: "yóu", meaning: "lame" },
  { char: "尸", pinyin: "shī", meaning: "corpse" },
  { char: "屮", pinyin: "chè", meaning: "sprout" },
  { char: "山", pinyin: "shān", meaning: "mountain" },
  { char: "巛", pinyin: "chuān", meaning: "river" },
  { char: "工", pinyin: "gōng", meaning: "work" },
  { char: "己", pinyin: "jǐ", meaning: "self" },
  { char: "巾", pinyin: "jīn", meaning: "turban" },
  { char: "干", pinyin: "gān", meaning: "dry" },
  { char: "幺", pinyin: "yāo", meaning: "short thread" },
  { char: "广", pinyin: "guǎng", meaning: "dotted cliff" },
  { char: "廴", pinyin: "yǐn", meaning: "long stride" },
  { char: "廾", pinyin: "gǒng", meaning: "two hands" },
  { char: "弋", pinyin: "yì", meaning: "shoot" },
  { char: "弓", pinyin: "gōng", meaning: "bow" },
  { char: "彐", pinyin: "jì", meaning: "snout" },
  { char: "彡", pinyin: "shān", meaning: "bristle" },
  { char: "彳", pinyin: "chì", meaning: "step" },
  { char: "心", pinyin: "xīn", meaning: "heart" },
  { char: "戈", pinyin: "gē", meaning: "halberd" },
  { char: "戶", pinyin: "hù", meaning: "door" },
  { char: "手", pinyin: "shǒu", meaning: "hand" },
  { char: "支", pinyin: "zhī", meaning: "branch" },
  { char: "攴", pinyin: "pū", meaning: "rap" },
  { char: "文", pinyin: "wén", meaning: "script" },
  { char: "斗", pinyin: "dǒu", meaning: "dipper" },
  { char: "斤", pinyin: "jīn", meaning: "axe" },
  { char: "方", pinyin: "fāng", meaning: "square" },
  { char: "无", pinyin: "wú", meaning: "not" },
  { char: "日", pinyin: "rì", meaning: "sun" },
  { char: "曰", pinyin: "yuē", meaning: "say" },
  { char: "月", pinyin: "yuè", meaning: "moon" },
  { char: "木", pinyin: "mù", meaning: "tree" },
  { char: "欠", pinyin: "qiàn", meaning: "lack" },
  { char: "止", pinyin: "zhǐ", meaning: "stop" },
  { char: "歹", pinyin: "dǎi", meaning: "death" },
  { char: "殳", pinyin: "shū", meaning: "weapon" },
  { char: "毋", pinyin: "wú", meaning: "do not" },
  { char: "比", pinyin: "bǐ", meaning: "compare" },
  { char: "毛", pinyin: "máo", meaning: "hair" },
  { char: "氏", pinyin: "shì", meaning: "clan" },
  { char: "气", pinyin: "qì", meaning: "steam" },
  { char: "水", pinyin: "shuǐ", meaning: "water" },
  { char: "火", pinyin: "huǒ", meaning: "fire" },
  { char: "爪", pinyin: "zhǎo", meaning: "claw" },
  { char: "父", pinyin: "fù", meaning: "father" },
  { char: "爻", pinyin: "yáo", meaning: "trigrams" },
  { char: "爿", pinyin: "qiáng", meaning: "half tree trunk" },
  { char: "片", pinyin: "piàn", meaning: "slice" },
  { char: "牙", pinyin: "yá", meaning: "fang" },
  { char: "牛", pinyin: "niú", meaning: "cow" },
  { char: "犬", pinyin: "quǎn", meaning: "dog" },
  { char: "玄", pinyin: "xuán", meaning: "profound" },
  { char: "玉", pinyin: "yù", meaning: "jade" },
  { char: "瓜", pinyin: "guā", meaning: "melon" },
  { char: "瓦", pinyin: "wǎ", meaning: "tile" },
  { char: "甘", pinyin: "gān", meaning: "sweet" },
  { char: "生", pinyin: "shēng", meaning: "life" },
  { char: "用", pinyin: "yòng", meaning: "use" },
  { char: "田", pinyin: "tián", meaning: "field" },
  { char: "疋", pinyin: "pǐ", meaning: "bolt of cloth" },
  { char: "疒", pinyin: "nè", meaning: "sickness" },
  { char: "癶", pinyin: "bō", meaning: "footsteps" },
  { char: "白", pinyin: "bái", meaning: "white" },
  { char: "皮", pinyin: "pí", meaning: "skin" },
  { char: "皿", pinyin: "mǐn", meaning: "dish" },
  { char: "目", pinyin: "mù", meaning: "eye" },
  { char: "矛", pinyin: "máo", meaning: "spear" },
  { char: "矢", pinyin: "shǐ", meaning: "arrow" },
  { char: "石", pinyin: "shí", meaning: "stone" },
  { char: "示", pinyin: "shì", meaning: "spirit" },
  { char: "禸", pinyin: "róu", meaning: "track" },
  { char: "禾", pinyin: "hé", meaning: "grain" },
  { char: "穴", pinyin: "xué", meaning: "cave" },
  { char: "立", pinyin: "lì", meaning: "stand" },
  { char: "竹", pinyin: "zhú", meaning: "bamboo" },
  { char: "米", pinyin: "mǐ", meaning: "rice" },
  { char: "糸", pinyin: "mì", meaning: "silk" },
  { char: "缶", pinyin: "fǒu", meaning: "jar" },
  { char: "网", pinyin: "wǎng", meaning: "net" },
  { char: "羊", pinyin: "yáng", meaning: "sheep" },
  { char: "羽", pinyin: "yǔ", meaning: "feather" },
  { char: "老", pinyin: "lǎo", meaning: "old" },
  { char: "而", pinyin: "ér", meaning: "and" },
  { char: "耒", pinyin: "lěi", meaning: "plow" },
  { char: "耳", pinyin: "ěr", meaning: "ear" },
  { char: "聿", pinyin: "yù", meaning: "brush" },
  { char: "肉", pinyin: "ròu", meaning: "meat" },
  { char: "臣", pinyin: "chén", meaning: "minister" },
  { char: "自", pinyin: "zì", meaning: "self" },
  { char: "至", pinyin: "zhì", meaning: "arrive" },
  { char: "臼", pinyin: "jiù", meaning: "mortar" },
  { char: "舌", pinyin: "shé", meaning: "tongue" },
  { char: "舛", pinyin: "chuǎn", meaning: "oppose" },
  { char: "舟", pinyin: "zhōu", meaning: "boat" },
  { char: "艮", pinyin: "gèn", meaning: "stopping" },
  { char: "色", pinyin: "sè", meaning: "color" },
  { char: "艸", pinyin: "cǎo", meaning: "grass" },
  { char: "虍", pinyin: "hū", meaning: "tiger stripes" },
  { char: "虫", pinyin: "chóng", meaning: "insect" },
  { char: "血", pinyin: "xuè", meaning: "blood" },
  { char: "行", pinyin: "xíng", meaning: "walk enclosure" },
  { char: "衣", pinyin: "yī", meaning: "clothes" },
  { char: "襾", pinyin: "yà", meaning: "west" },
  { char: "見", pinyin: "jiàn", meaning: "see" },
  { char: "角", pinyin: "jiǎo", meaning: "horn" },
  { char: "言", pinyin: "yán", meaning: "speech" },
  { char: "谷", pinyin: "gǔ", meaning: "valley" },
  { char: "豆", pinyin: "dòu", meaning: "bean" },
  { char: "豕", pinyin: "shǐ", meaning: "pig" },
  { char: "豸", pinyin: "zhì", meaning: "badger" },
  { char: "貝", pinyin: "bèi", meaning: "shell" },
  { char: "赤", pinyin: "chì", meaning: "red" },
  { char: "走", pinyin: "zǒu", meaning: "run" },
  { char: "足", pinyin: "zú", meaning: "foot" },
  { char: "身", pinyin: "shēn", meaning: "body" },
  { char: "車", pinyin: "chē", meaning: "cart" },
  { char: "辛", pinyin: "xīn", meaning: "bitter" },
  { char: "辰", pinyin: "chén", meaning: "morning" },
  { char: "辵", pinyin: "chuò", meaning: "walk" },
  { char: "邑", pinyin: "yì", meaning: "city" },
  { char: "酉", pinyin: "yǒu", meaning: "wine" },
  { char: "釆", pinyin: "biàn", meaning: "distinguish" },
  { char: "里", pinyin: "lǐ", meaning: "village" },
  { char: "金", pinyin: "jīn", meaning: "gold" },
  { char: "長", pinyin: "cháng", meaning: "long" },
  { char: "門", pinyin: "mén", meaning: "gate" },
  { char: "阜", pinyin: "fù", meaning: "mound" },
  { char: "隶", pinyin: "lì", meaning: "slave" },
  { char: "隹", pinyin: "zhuī", meaning: "short-tailed bird" },
  { char: "雨", pinyin: "yǔ", meaning: "rain" },
  { char: "靑", pinyin: "qīng", meaning: "blue" },
  { char: "非", pinyin: "fēi", meaning: "wrong" },
  { char: "面", pinyin: "miàn", meaning: "face" },
  { char: "革", pinyin: "gé", meaning: "leather" },
  { char: "韋", pinyin: "wéi", meaning: "tanned leather" },
  { char: "韭", pinyin: "jiǔ", meaning: "leek" },
  { char: "音", pinyin: "yīn", meaning: "sound" },
  { char: "頁", pinyin: "yè", meaning: "leaf" },
  { char: "風", pinyin: "fēng", meaning: "wind" },
  { char: "飛", pinyin: "fēi", meaning: "fly" },
  { char: "食", pinyin: "shí", meaning: "eat" },
  { char: "首", pinyin: "shǒu", meaning: "head" },
  { char: "香", pinyin: "xiāng", meaning: "fragrant" },
  { char: "馬", pinyin: "mǎ", meaning: "horse" },
  { char: "骨", pinyin: "gǔ", meaning: "bone" },
  { char: "高", pinyin: "gāo", meaning: "tall" },
  { char: "髟", pinyin: "biāo", meaning: "hair" },
  { char: "鬥", pinyin: "dòu", meaning: "fight" },
  { char: "鬯", pinyin: "chàng", meaning: "sacrificial wine" },
  { char: "鬲", pinyin: "lì", meaning: "cauldron" },
  { char: "鬼", pinyin: "guǐ", meaning: "ghost" },
  { char: "魚", pinyin: "yú", meaning: "fish" },
  { char: "鳥", pinyin: "niǎo", meaning: "bird" },
  { char: "鹵", pinyin: "lǔ", meaning: "salt" },
  { char: "鹿", pinyin: "lù", meaning: "deer" },
  { char: "麥", pinyin: "mài", meaning: "wheat" },
  { char: "麻", pinyin: "má", meaning: "hemp" },
  { char: "黃", pinyin: "huáng", meaning: "yellow" },
  { char: "黍", pinyin: "shǔ", meaning: "millet" },
  { char: "黑", pinyin: "hēi", meaning: "black" },
  { char: "黹", pinyin: "zhǐ", meaning: "embroidery" },
  { char: "黽", pinyin: "mǐn", meaning: "frog" },
  { char: "鼎", pinyin: "dǐng", meaning: "tripod" },
  { char: "鼓", pinyin: "gǔ", meaning: "drum" },
  { char: "鼠", pinyin: "shǔ", meaning: "rat" },
  { char: "鼻", pinyin: "bí", meaning: "nose" },
  { char: "齊", pinyin: "qí", meaning: "even" },
  { char: "齒", pinyin: "chǐ", meaning: "tooth" },
  { char: "龍", pinyin: "lóng", meaning: "dragon" },
  { char: "龜", pinyin: "guī", meaning: "turtle" },
  { char: "龠", pinyin: "yuè", meaning: "flute" }
];

export const NUMBERS_DATA: CharacterData[] = [
  { char: "零", pinyin: "líng", meaning: "zero" },
  { char: "一", pinyin: "yī", meaning: "one" },
  { char: "二", pinyin: "èr", meaning: "two" },
  { char: "三", pinyin: "sān", meaning: "three" },
  { char: "四", pinyin: "sì", meaning: "four" },
  { char: "五", pinyin: "wǔ", meaning: "five" },
  { char: "六", pinyin: "liù", meaning: "six" },
  { char: "七", pinyin: "qī", meaning: "seven" },
  { char: "八", pinyin: "bā", meaning: "eight" },
  { char: "九", pinyin: "jiǔ", meaning: "nine" },
  { char: "十", pinyin: "shí", meaning: "ten" }
];

export const ANIMALS: Animal[] = [
  { emoji: "🐼", name: "Panda", message: "You're doing great!" },
  { emoji: "🐯", name: "Tiger", message: "Keep fighting!" },
  { emoji: "🦊", name: "Fox", message: "Clever choice!" },
  { emoji: "🐰", name: "Rabbit", message: "Fast learner!" },
  { emoji: "🦁", name: "Lion", message: "Roaring success!" },
  { emoji: "🐨", name: "Koala", message: "Stay calm and study." },
  { emoji: "🦉", name: "Owl", message: "Wise moves." },
  { emoji: "🐸", name: "Frog", message: "Hop to it!" }
];
